<a href="https://colab.research.google.com/github/Bansariahir123/Telecom-customer-churn-using-logistic-regression/blob/main/Telcocustomerchurn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Telecom customer churn using logistic regression

In [71]:
import pandas as pd
data = pd.read_csv('/content/churn-bigml-20.csv')  # Dataset from kaggle Telco Customer Churn-LogisticRegression
data

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,415,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False
663,AL,106,408,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False
664,VT,60,415,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False
665,WV,159,415,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
666,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

In [72]:
data["Churn"]= pd.Categorical(data["Churn"]).codes
data["Voice mail plan"] = pd.Categorical(data["Voice mail plan"]).codes
data["International plan"] = pd.Categorical(data["International plan"]).codes
data["State"]= pd.Categorical(data["State"]).codes
data

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,18,117,408,0,0,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,0
1,15,65,415,0,0,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,1
2,34,161,415,0,0,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,1
3,40,111,415,0,0,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,0
4,11,49,510,0,0,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,48,114,415,0,1,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,0
663,1,106,408,0,1,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,0
664,46,60,415,0,0,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,0
665,49,159,415,0,0,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,0
666,6,184,510,1,0,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,0

In [73]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import GridSearchCV
import joblib

# Load the dataset
data = pd.read_csv('/content/churn-bigml-20.csv')  # Replace with your dataset's filename
data
# Data Preprocessing
# Handle missing data and outliers if needed
# ...
data["Churn"]= pd.Categorical(data["Churn"]).codes
data["Voice mail plan"] = pd.Categorical(data["Voice mail plan"]).codes
data["International plan"] = pd.Categorical(data["International plan"]).codes
data["State"]= pd.Categorical(data["State"]).codes
data
# Prepare the data
X = data.drop('Churn', axis=1)
y = data['Churn']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature Engineering
# Generate relevant features if needed
# Apply feature scaling or normalization
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model Building
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Model Evaluation
y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Model Accuracy:", accuracy)
print("Classification Report:\n", classification_rep)

# Model Optimization
# We can also perform hyperparameter tuning using techniques like GridSearchCV
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10]}
grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)
best_model = grid_search.best_estimator_
best_params = grid_search.best_params_

# Model Deployment
# Save the trained model using joblib
joblib.dump(best_model, 'churn_model.pkl')

# Load the model for deployment
loaded_model = joblib.load('churn_model.pkl')

# Simulate model deployment
# Input new customer data and get churn prediction

Model Accuracy: 0.917910447761194
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.97      0.95       119
           1       0.70      0.47      0.56        15

    accuracy                           0.92       134
   macro avg       0.82      0.72      0.76       134
weighted avg       0.91      0.92      0.91       134

In [75]:
# State, International plan, Voice mail plan were encoded, so keep input according to encoded values
new_customer_data = pd.DataFrame({
    'State': [2],
    'Account length': [160],
    'Area code': [415],
    'International plan': [0],
    'Voice mail plan': [1],
    'Number vmail messages': [0],
    'Total day minutes': [83],
    'Total day calls': [20],
    'Total day charge': [57],
    'Total eve minutes': [280.3],
    'Total eve calls': [90],
    'Total eve charge': [18.75],
    'Total night minutes': [180.2],
    'Total night calls': [100],
    'Total night charge': [8.11],
    'Total intl minutes': [10.5],
    'Total intl calls': [4],
    'Total intl charge': [2.84],
    'Customer service calls': [1]
})
new_customer_scaled = scaler.transform(new_customer_data)
churn_prediction = loaded_model.predict(new_customer_scaled)
print("Churn Prediction for New Customer:", churn_prediction)
new_customer_scaled = scaler.transform(new_customer_data)
churn_prediction_encoded = loaded_model.predict(new_customer_scaled)

churn_prediction = ['True' if prediction == 1 else 'False' for prediction in churn_prediction_encoded]
print("Churn Prediction for New Customer:", churn_prediction)

Churn Prediction for New Customer: [0]
Churn Prediction for New Customer: ['False']